"""Initial migration

Revision ID: 95fea482757c
Revises: 
Create Date: 2025-07-11 21:20:09.124637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95fea482757c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('etiquetas', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=False)
    op.create_index(op.f('ix_clientes_nome'), 'clientes', ['nome'], unique=False)
    op.create_table('pacotes_servicos',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('servicos_ids', sa.Text(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacotes_servicos_ativo'), 'pacotes_servicos', ['ativo'], unique=False)
    op.create_index(op.f('ix_pacotes_servicos_nome'), 'pacotes_servicos', ['nome'], unique=False)
    op.create_table('servicos',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('duracao_minutos', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicos_ativo'), 'servicos', ['ativo'], unique=False)
    op.create_index(op.f('ix_servicos_nome'), 'servicos', ['nome'], unique=False)
    op.create_table('usuarios',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('agendamentos',
    sa.Column('cliente_id', sa.String(length=36), nullable=False),
    sa.Column('servico_id', sa.String(length=36), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendamentos_cliente_id'), 'agendamentos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_agendamentos_data_hora_inicio'), 'agendamentos', ['data_hora_inicio'], unique=False)
    op.create_index(op.f('ix_agendamentos_servico_id'), 'agendamentos', ['servico_id'], unique=False)
    op.create_index(op.f('ix_agendamentos_status'), 'agendamentos', ['status'], unique=False)
    op.create_table('precos_personalizados',
    sa.Column('cliente_id', sa.String(length=36), nullable=False),
    sa.Column('servico_id', sa.String(length=36), nullable=False),
    sa.Column('preco_personalizado', sa.Float(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_precos_personalizados_ativo'), 'precos_personalizados', ['ativo'], unique=False)
    op.create_index(op.f('ix_precos_personalizados_cliente_id'), 'precos_personalizados', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_precos_personalizados_servico_id'), 'precos_personalizados', ['servico_id'], unique=False)
    op.create_table('pagamentos',
    sa.Column('agendamento_id', sa.String(length=36), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('metodo_pagamento', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('link_pagamento', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamentos_agendamento_id'), 'pagamentos', ['agendamento_id'], unique=False)
    op.create_index(op.f('ix_pagamentos_metodo_pagamento'), 'pagamentos', ['metodo_pagamento'], unique=False)
    op.create_index(op.f('ix_pagamentos_status'), 'pagamentos', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagamentos_status'), table_name='pagamentos')
    op.drop_index(op.f('ix_pagamentos_metodo_pagamento'), table_name='pagamentos')
    op.drop_index(op.f('ix_pagamentos_agendamento_id'), table_name='pagamentos')
    op.drop_table('pagamentos')
    op.drop_index(op.f('ix_precos_personalizados_servico_id'), table_name='precos_personalizados')
    op.drop_index(op.f('ix_precos_personalizados_cliente_id'), table_name='precos_personalizados')
    op.drop_index(op.f('ix_precos_personalizados_ativo'), table_name='precos_personalizados')
    op.drop_table('precos_personalizados')
    op.drop_index(op.f('ix_agendamentos_status'), table_name='agendamentos')
    op.drop_index(op.f('ix_agendamentos_servico_id'), table_name='agendamentos')
    op.drop_index(op.f('ix_agendamentos_data_hora_inicio'), table_name='agendamentos')
    op.drop_index(op.f('ix_agendamentos_cliente_id'), table_name='agendamentos')
    op.drop_table('agendamentos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_servicos_nome'), table_name='servicos')
    op.drop_index(op.f('ix_servicos_ativo'), table_name='servicos')
    op.drop_table('servicos')
    op.drop_index(op.f('ix_pacotes_servicos_nome'), table_name='pacotes_servicos')
    op.drop_index(op.f('ix_pacotes_servicos_ativo'), table_name='pacotes_servicos')
    op.drop_table('pacotes_servicos')
    op.drop_index(op.f('ix_clientes_nome'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
